# Generated by Django 4.2.2 on 2024-12-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
    ]
