board_games = [
  {
    'id': 1,
    'title': 'Монополия',
    'description': 'Классическая экономическая настольная игра.',
    'genres': ['Экономика', 'Стратегия'],
    'players': '2-6',
    'min_players': 2,
    'max_players': 6,
    'duration': '1-2 часа',
    'image_url': 'https://www.mosigra.ru/image/cache/data/mosigra.product.box/558/968/1-1024x1024-wm.webp',
  },
  {
    'id': 2,
    'title': 'Каркассон',
    'description': 'Игра, в которой участники строят карту средневекового города.',
    'genres': ['Стратегия', 'Пазлы'],
    'players': '2-5',
    'min_players': 2,
    'max_players': 5,
    'duration': '30-60 минут',
    'image_url': 'https://hobbygames.kz/image/cache/hobbygames_beta/data/HobbyWorld/Karkasson/2019/Korolevsky_Podarok2019/Photos/carcassonne_present00-1024x1024-wm.jpg',
  },
  {
    'id': 3,
    'title': 'Колонизаторы',
    'description': 'Игра на строительство поселений и торговлю ресурсами.',
    'genres': ['Экономика', 'Стратегия'],
    'players': '3-4',
    'min_players': 3,
    'max_players': 4,
    'duration': '1-2 часа',
    'image_url': 'https://simg.marwin.kz/media/catalog/product/cache/41deb699a7fea062a8915debbbb0442c/7/6/762521_1000.jpg',
  },
  {
    'id': 4,
    'title': 'Имаджинариум',
    'description': 'Ассоциативная игра для фантазеров.',
    'genres': ['Семейная', 'Воображение'],
    'players': '4-7',
    'min_players': 4,
    'max_players': 7,
    'duration': '30-90 минут',
    'image_url': 'https://cosmodrome.games/upload/resize_cache/iblock/165/500_400_1/1656b07c274f57acdfb8b363ded1abca.jpg',
  },
  {
    'id': 5,
    'title': 'Диксит',
    'description': 'Игра на создание историй по иллюстрациям.',
    'genres': ['Семейная', 'Креативность'],
    'players': '3-6',
    'min_players': 3,
    'max_players': 6,
    'duration': '30-60 минут',
    'image_url': 'https://www.mosigra.ru/image/cache/data/%D0%9F%D1%80%D0%B5%D0%B4%D0%B2%D0%B0%D1%80%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5%20%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D1%8B/%D0%A1%D1%82%D0%B8%D0%BB%D1%8C%20%D0%B6%D0%B8%D0%B7%D0%BD%D0%B8/%D0%94%D0%B8%D0%BA%D1%81%D0%B8%D1%82/Dixit-1024x1024-1024x1024-wm.webp',
  },
  {
    'id': 6,
    'title': 'Манчкин',
    'description': 'Смешная карточная игра на исследование подземелий.',
    'genres': ['Ролевая', 'Юмор'],
    'players': '3-6',
    'min_players': 3,
    'max_players': 6,
    'duration': '1-2 часа',
    'image_url': 'https://hobbyworld.cdnvideo.ru/image/cache/hobbyworld/data/HobbyWorld/Munchkin/Munchkin/Munchkin00-1200x800-wm.jpg',
  },
  {
    'id': 7,
    'title': 'Уно',
    'description': 'Классическая карточная игра.',
    'genres': ['Семейная', 'Карточная'],
    'players': '2-10',
    'min_players': 2,
    'max_players': 10,
    'duration': '30 минут',
    'image_url': 'https://simg.marwin.kz/media/catalog/product/cache/41deb699a7fea062a8915debbbb0442c/3/4/347669_4.jpg',
  },
  {
    'id': 8,
    'title': 'Риск',
    'description': 'Классическая игра на завоевание мира.',
    'genres': ['Стратегия', 'Война'],
    'players': '2-6',
    'min_players': 2,
    'max_players': 6,
    'duration': '2-4 часа',
    'image_url': 'https://ae04.alicdn.com/kf/S87e4d68a24144e0db4dfe0c5591fb5ba0.jpg_480x480.jpg',
  },
  {
    'id': 9,
    'title': 'Цивилизация',
    'description': 'Игра по мотивам известной компьютерной стратегии.',
    'genres': ['Стратегия', 'История'],
    'players': '2-4',
    'min_players': 2,
    'max_players': 4,
    'duration': '2-4 часа',
    'image_url': 'https://hobbygames.kz/image/cache/hobbygames_beta/hg/3/2/32457-1024x1024-wm.jpg',
  },
  {
    'id': 10,
    'title': 'Эволюция',
    'description': 'Игра на выживание и развитие видов.',
    'genres': ['Стратегия', 'Научная'],
    'players': '2-6',
    'min_players': 2,
    'max_players': 6,
    'duration': '30-60 минут',
    'image_url': 'https://images.satu.kz/142944871_nastolnaya-igra-evolyutsiya.jpg',
  },
  {
    'id': 11,
    'title': 'Саботёр',
    'description': 'Карточная игра о шахтёрах и саботажниках.',
    'genres': ['Семейная', 'Ролевая'],
    'players': '3-10',
    'min_players': 3,
    'max_players': 10,
    'duration': '30-60 минут',
    'image_url': 'https://lv2.pigugroup.eu/colours/729/656/729656/e6a0247cd2b9773c40c363f7ff6cf3d5_reference.jpg',
  },
  {
    'id': 12,
    'title': 'Alias',
    'description': 'Игра на объяснение слов с помощью ассоциаций.',
    'genres': ['Семейная', 'Командная'],
    'players': '4+',
    'min_players': 4,
    'max_players': 20,
    'duration': '30-60 минут',
    'image_url': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMC2F0lc4E6YOIYGVzi_PNUexpBOmJWOVwBw&s',
  },
  {
    'id': 13,
    'title': 'Шакал',
    'description': 'Игра на поиск сокровищ.',
    'genres': ['Приключения', 'Стратегия'],
    'players': '2-4',
    'min_players': 2,
    'max_players': 4,
    'duration': '2-3 часа',
    'image_url': 'https://simg.marwin.kz/media/catalog/product/migrated/article/6839/11_tn3.jpg',
  },
  {
    'id': 14,
    'title': 'Мафия',
    'description': 'Классическая игра на роль и интригу.',
    'genres': ['Ролевая', 'Семейная'],
    'players': '5-20',
    'min_players': 5,
    'max_players': 20,
    'duration': '30-60 минут',
    'image_url': 'https://simg.marwin.kz/media/catalog/product/cache/41deb699a7fea062a8915debbbb0442c/migrated/article/8695/13_tn3.jpg',
  },
  {
    'id': 15,
    'title': 'Скраббл',
    'description': 'Игра на составление слов.',
    'genres': ['Словесная', 'Образовательная'],
    'players': '2-4',
    'min_players': 2,
    'max_players': 4,
    'duration': '30-60 минут',
    'image_url': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkDJSWlMjH_zTXYLCi1MmeA0e5UI-eeA4CCw&s',
  },
  {
    'id': 16,
    'title': 'Пандемия',
    'description': 'Кооперативная игра на спасение мира от вирусов.',
    'genres': ['Стратегия', 'Кооперативная'],
    'players': '2-4',
    'min_players': 2,
    'max_players': 4,
    'duration': '1-2 часа',
    'image_url': 'https://images.satu.kz/212015807_w200_h200_pandemiya.jpg',
  },
  {
    'id': 17,
    'title': 'Домино',
    'description': 'Классическая игра с костяшками.',
    'genres': ['Классика', 'Семейная'],
    'players': '2-4',
    'min_players': 2,
    'max_players': 4,
    'duration': '30 минут',
    'image_url': 'https://ir-3.ozone.ru/s3/multimedia-1-z/c1000/6924751559.jpg',
  },
  {
    'id': 18,
    'title': 'Аркхэм Хоррор',
    'description': 'Игра в мире мифов Ктулху.',
    'genres': ['Приключения', 'Ужасы'],
    'players': '1-8',
    'min_players': 1,
    'max_players': 8,
    'duration': '2-4 часа',
    'image_url': 'https://hobbygames.kz/image/cache/hobbygames_beta/data/HobbyWorld/Ujas_Arkhema/UA_cardgame/JKI_UjasArkhama-1024x1024-wm.jpg',
  },
  {
    'id': 19,
    'title': 'Башня',
    'description': 'Игра на ловкость с деревянными блоками.',
    'genres': ['Семейная', 'Ловкость'],
    'players': '2+',
    'min_players': 2,
    'max_players': 20,
    'duration': '30 минут',
    'image_url': 'https://images.satu.kz/49090871_w600_h600_49090871.jpg',
  },
  {
    'id': 20,
    'title': 'Зомбицыд',
    'description': 'Кооперативная игра про выживание.',
    'genres': ['Стратегия', 'Ужасы'],
    'players': '1-6',
    'min_players': 1,
    'max_players': 6,
    'duration': '1-3 часа',
    'image_url': 'https://small-bunny.com.ua/content/images/6/nastolnaja-igra-zombicid-75270112390666_small11.jpg',
  },
  {
    'id': 21,
    'title': 'Дженга',
    'description': 'Игра на строительство башни из деревянных блоков.',
    'genres': ['Ловкость', 'Семейная'],
    'players': '1+',
    'min_players': 1,
    'max_players': 10,
    'duration': '10-30 минут',
    'image_url': 'https://catalog.detmir.st/media/uiHW6ihrbrPSSaoJoS59-e0K8fqNsFfsvi2eLhg3oPc=?preset=site_product_gallery_r1500',
  },
  {
    'id': 22,
    'title': 'Серп',
    'description': 'Игра в альтернативной реальности Восточной Европы.',
    'genres': ['Стратегия', 'Экономика'],
    'players': '1-5',
    'min_players': 1,
    'max_players': 5,
    'duration': '1-2 часа',
    'image_url': 'https://hobbygames.kz/image/cache/hobbygames_beta/data/CrowD_Games/Scythe/scythe_box-1024x1024-wm.jpg',
  },
  {
    'id': 23,
    'title': 'Мемо',
    'description': 'Игра на развитие памяти.',
    'genres': ['Образовательная', 'Семейная'],
    'players': '2+',
    'min_players': 2,
    'max_players': 10,
    'duration': '20-40 минут',
    'image_url': 'https://simg.marwin.kz/media/catalog/product/cache/8d1771fdd19ec2393e47701ba45e606d/2/f/neskuchnye_igry_memo_kazahstan.jpg',
  },
  {
    'id': 24,
    'title': 'Тик-так-бум',
    'description': 'Игра на составление слов под давлением времени.',
    'genres': ['Семейная', 'Словесная'],
    'players': '2-12',
    'min_players': 2,
    'max_players': 12,
    'duration': '30 минут',
    'image_url': 'https://catalog.detmir.st/media/ZIEZzihWTqMEo1yvNlBy6RKDBHGVWeqPNUo45SJQP2w=?preset=site_product_gallery_r1500',
  },
];
